### PR TITLE
Fix typo in the EventQuarter Report 

### PR DESCRIPTION
**Pull request by monishdeb**

### CODE REVIEW

**Comment by JoeMurray** [comment]
Please provide functional not generic description of change to assist in QA process.

**Review by JoeMurray — COMMENTED** [review]
Is this a syntactically incorrect line fragment?

**Comment by monishdeb** [comment]
Yes it is. Which I noticed while reviewing the RTF report and made a quick fix to resolve it.

**Comment by JoeMurray** [comment]
Thx

**Pull request merged**
